[package]
name = "smh"
version = "0.1.0"
authors = ["Jack Pearson <jack@pearson.onl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mac_address = "^1.1.1"
ipaddress = "^0.1.2"
anyhow = "^1.0.40"